name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: cargo test
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
