name: DevContainer

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-devcontainer:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set lowercase repository name
        id: lowercase
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ steps.lowercase.outputs.repo }}/devcontainer
          cacheFrom: ghcr.io/${{ steps.lowercase.outputs.repo }}/devcontainer
          push: always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}